apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa1-scielo-br

resources:
  - ../base

images:
  - name: rondinelisaad/opac
    newName: rondinelisaad/opac
    digest: sha256:1eb222cd8cb5671eef0ab93ab1658a0c848bbc376f5de093f264811ae531908e
