apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa1-scielo-br

resources:
  - ../base

images:
  - name: rondinelisaad/opac
    newName: rondinelisaad/opac
    digest: sha256:a56f8b36c2243bf939922aee5a620b50691da36a5920137e37279edd76892bd1
